chore: Update PHP version to 8.3 in Dockerfile

diff --git a/run b/run
--- a/run
+++ b/run
@@ -7,76 +7,98 @@ REMOTE_PATH=/root/topquote.nl
 REGISTRY_URL="registry.mmsrv.nl"
 
 dev() {
-    docker-compose up -d --force-recreate --build
+    docker compose \
+        -f docker-compose.yml \
+        -f docker-compose.override.yml \
+        up -d --force-recreate --build
 }
 
 stopdev() {
-    docker-compose down --remove-orphans
+    docker compose \
+        -f docker-compose.yml \
+        -f docker-compose.override.yml \
+        down --remove-orphans
 }
 
 console() {
-    docker exec -it topquote-php bash
+    docker compose exec -it php bash
+}
+
+compile() {
+    npm run build
+    # docker run --platform linux/amd64 --rm -it \
+    #     -v .:/project \
+    #     -w /project \
+    #     --tmpfs /project/node_modules \
+    #     node:20-slim sh -c "npm i && npm run build"
 }
 
 build() {
-    docker run --platform linux/amd64 --rm -it -v .:/project -w /project node:20-slim sh -c "npm i && npm run build"  
     docker buildx build --platform linux/amd64 --tag ${REGISTRY_URL}/topquote-php:latest --push ./app
     docker buildx build --platform linux/amd64 --tag ${REGISTRY_URL}/topquote-nginx:latest --push ./nginx 
 }
 
-clear_caches() {
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && bin/clear-caches"
+clear_remote_caches() {
+    ssh "$REMOTE_USER"@$REMOTE_HOST "docker compose exec php bash -c "rm -rf /var/www/{cache,templates/cache}/* && chmod -R 777 /var/www/{cache,templates/cache}""
 }
 
 deploy() {
-    build
+    # exit on errors
+    set -e
+    # ask to create image 
+    read -p "Do you want to create a new docker image? (y/n) " -n 1 -r
+    echo
+    # compile assets
+    compile
+    # build images
+    if [[ $REPLY =~ ^[Yy]$ ]]
+    then
+        build
+        sleep 5
+    fi
+    # pull new images on production server
+    if [[ $REPLY =~ ^[Yy]$ ]]
+    then
+        ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker pull registry.mmsrv.nl/topquote-nginx:latest && docker pull registry.mmsrv.nl/topquote-php:latest"
+        sleep 2
+    fi
+    # bring down production
     ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans"
-    ssh "$REMOTE_USER"@$REMOTE_HOST mkdir -p $REMOTE_PATH/{app,bin,import}
+    # first time 
+    ssh "$REMOTE_USER"@$REMOTE_HOST mkdir -p $REMOTE_PATH/app
+    # copy files
     scp docker-compose{.prod.yml,.yml} "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/
     scp .env.production "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/.env
-    scp bin/{prod,dbdump,clear-caches} "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/bin/
+    # upload new code
     rsync -rz -e ssh app/ "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/app/ --exclude 'public/sitemap*'  --delete
-    rsync -rz -e ssh import/ "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/import/ --delete
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && bin/prod"
+    # bring up production
+    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d"
     sleep 10
-    clear_caches
+    # continue on errors 
+    set +e
+    # clear caches
+    clear_remote_caches
     sleep 5
+    # generate sitemap
     ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && rm -rf app/public/sitemap*"
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker exec topquote-php php /var/www/bin/sitemap.php" 
+    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker compose -f docker-compose.yml -f docker-compose.prod.yml exec php php /var/www/bin/sitemap.php" 
 }
 
-deploy_no_build() {
-    docker run --platform linux/amd64 --rm -it -v .:/project -w /project node:20-slim sh -c "npm i && npm run build"  
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans"
-    ssh "$REMOTE_USER"@$REMOTE_HOST mkdir -p $REMOTE_PATH/{app,bin,import}
-    scp docker-compose{.prod.yml,.yml} "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/
-    scp .env.production "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/.env
-    scp bin/{prod,dbdump,clear-caches} "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/bin/
-    rsync -rz -e ssh app/ "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/app/ --exclude 'public/sitemap*'  --delete
-    rsync -rz -e ssh import/ "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/import/ --delete
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && bin/prod"
-    sleep 10
-    clear_caches
-    sleep 5
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && rm -rf app/public/sitemap*"
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker exec topquote-php php /var/www/bin/sitemap.php" 
+dbdump() {
+    # docker exec topquote-mysql sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > dump.sql
+    WORK_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+    cd $WORK_DIR
+    TIMESTAMP=$(date +%Y%m%d%H%M%S)
+    set -o allexport
+    source .env
+    set +o allexport
+    BACKUP_DIR="${WORK_DIR}/mount/backups/db"
+    mkdir -p ${BACKUP_DIR}
+    BACKUP_FILE_NAME="${BACKUP_DIR}/${DB_NAME}-${TIMESTAMP}.sql"
+    docker exec topquote-db bash -c \
+        "exec mysqldump --no-create-db -h"db" -u"${DB_USER}" -p"${DB_PASSWORD}" ${DB_NAME}" > ${BACKUP_FILE_NAME};
 }
 
-deploy_code_only() {
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker compose -f docker-compose.yml -f docker-compose.prod.yml down --remove-orphans"
-    ssh "$REMOTE_USER"@$REMOTE_HOST mkdir -p $REMOTE_PATH/{app,bin,import}
-    scp docker-compose{.prod.yml,.yml} "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/
-    scp .env.production "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/.env
-    scp bin/{prod,dbdump,clear-caches} "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/bin/
-    rsync -rz -e ssh app/ "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/app/ --exclude 'public/sitemap*'  --delete
-    rsync -rz -e ssh import/ "$REMOTE_USER"@$REMOTE_HOST:$REMOTE_PATH/import/ --delete
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && bin/prod"
-    sleep 10
-    clear_caches
-    sleep 5
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && rm -rf app/public/sitemap*"
-    ssh "$REMOTE_USER"@$REMOTE_HOST "cd $REMOTE_PATH && docker exec topquote-php php /var/www/bin/sitemap.php" 
-}
 
 # Check if a command is provided as an argument
 if [ $# -eq 1 ]; then
@@ -92,20 +114,20 @@ if [ $# -eq 1 ]; then
         "console")
             console
             ;;
-        "clear_caches")
-            clear_caches
+        "dbdump")
+            dbdump
+            ;;
+        "clear_remote_caches")
+            clear_remote_caches
             ;;
         "build")
             build
             ;;
+        "compile")
+            compile
+            ;;
         "deploy")
             deploy
-            ;;
-        "deploy_no_build")
-            deploy_no_build
-            ;;
-        "deploy_code_only")
-            deploy_code_only
             ;;
         *)
             echo "Invalid command: $command"
@@ -115,12 +137,12 @@ else
     # Display the list of available commands with explanations
     echo "Available commands"
     echo "----------------------"
-    echo "  run dev              -  Start local development"
-    echo "  run stopdev          -  Stop local development"
-    echo "  run console          -  Run console in container"
-    echo "  run clear_caches     -  Run console in container"
-    echo "  run build            -  Build, tag and push Docker images to the registry"
-    echo "  run deploy           -  Build, tag, push, pull and start containers on the production server"
-    echo "  run deploy_no_build  -  Compile styles, copy code and start containers on the production server"
-    echo "  run deploy_code_only -  Copy code and start containers on the production server"
+    echo "  ./run dev                   - Start local development"
+    echo "  ./run stopdev               - Stop local development"
+    echo "  ./run console               - Run console in container"
+    echo "  ./run dbdump                - Create a database dump"
+    echo "  ./run compile               - Compile assets"
+    echo "  ./run build                 - Build, tag and push Docker images to the registry"
+    echo "  ./run deploy                - Build, tag, push, pull and start containers on the production server"
+    echo "  ./run clear_remote_caches   - Clear production caches"
 fi
